# Translations template for heat.
# Copyright (C) 2013 ORGANIZATION
# This file is distributed under the same license as the heat project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2013.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: heat 2013.2.a430.gd264018\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2013-08-27 11:15+0800\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.6\n"

#: heat/api/aws/ec2token.py:38
msgid "Authentication Endpoint URI"
msgstr ""

#: heat/api/cfn/v1/stacks.py:260
#, python-format
msgid "Failed to fetch template: %s"
msgstr ""

#: heat/api/cfn/v1/stacks.py:293
msgid "DisableRollback and OnFailure may not be used together"
msgstr ""

#: heat/api/cfn/v1/stacks.py:313
#, python-format
msgid "Unexpected action %(action)s"
msgstr ""

#: heat/api/cfn/v1/stacks.py:331 heat/api/cfn/v1/stacks.py:413
msgid "Invalid Template URL"
msgstr ""

#: heat/api/cfn/v1/stacks.py:335 heat/api/cfn/v1/stacks.py:416
msgid "TemplateBody or TemplateUrl were not given."
msgstr ""

#: heat/api/cfn/v1/stacks.py:341 heat/api/cfn/v1/stacks.py:422
msgid "The Template must be a JSON or YAML document."
msgstr ""

#: heat/api/cfn/v1/stacks.py:383
msgid "stack not not found"
msgstr ""

#: heat/api/middleware/version_negotiation.py:49
#, python-format
msgid "Processing request: %(method)s %(path)s Accept: %(accept)s"
msgstr ""

#: heat/api/middleware/version_negotiation.py:64
#, python-format
msgid "Matched versioned URI. Version: %(major_version)d.%(minor_version)d"
msgstr ""

#: heat/api/middleware/version_negotiation.py:72
#, python-format
msgid ""
"Unknown version in versioned URI: %(major_version)d.%(minor_version)d. "
"Returning version choices."
msgstr ""

#: heat/api/middleware/version_negotiation.py:88
#, python-format
msgid "Matched versioned media type. Version: %(major_version)d.%(minor_version)d"
msgstr ""

#: heat/api/middleware/version_negotiation.py:94
#, python-format
msgid ""
"Unknown version in accept header: "
"%(major_version)d.%(minor_version)d...returning version choices."
msgstr ""

#: heat/api/middleware/version_negotiation.py:102
#, python-format
msgid "Unknown accept header: %s...returning version choices."
msgstr ""

#: heat/api/openstack/v1/actions.py:43
msgid "No action specified"
msgstr ""

#: heat/api/openstack/v1/actions.py:46
msgid "Multiple actions specified"
msgstr ""

#: heat/api/openstack/v1/actions.py:50
#, python-format
msgid "Invalid action %s specified"
msgstr ""

#: heat/api/openstack/v1/actions.py:57
#, python-format
msgid "Unexpected action %s"
msgstr ""

#: heat/api/openstack/v1/events.py:100
#, python-format
msgid "No events found for resource %s"
msgstr ""

#: heat/api/openstack/v1/events.py:118
#, python-format
msgid "No event %s found"
msgstr ""

#: heat/api/openstack/v1/stacks.py:75
#, python-format
msgid "%s not in valid format"
msgstr ""

#: heat/api/openstack/v1/stacks.py:83
msgid "No stack name specified"
msgstr ""

#: heat/api/openstack/v1/stacks.py:101
#, python-format
msgid "Could not retrieve template: %s"
msgstr ""

#: heat/api/openstack/v1/stacks.py:104
msgid "No template specified"
msgstr ""

#: heat/api/openstack/v1/util.py:56
msgid "Invalid Stack address"
msgstr ""

#: heat/common/auth_password.py:116
msgid "Request missing required header X-Auth-Url"
msgstr ""

#: heat/common/auth_password.py:121
#, python-format
msgid "Header X-Auth-Url \"%s\" not an allowed endpoint"
msgstr ""

#: heat/common/config.py:37
msgid "The flavor to use"
msgstr ""

#: heat/common/config.py:39
msgid "The API paste config file to use"
msgstr ""

#: heat/common/config.py:102
msgid "Allow orchestration of multiple clouds"
msgstr ""

#: heat/common/config.py:105
msgid ""
"Allowed keystone endpoints for auth_uri when multi_cloud is enabled. At "
"least one endpoint needs to be specified."
msgstr ""

#: heat/common/exception.py:102
msgid "An unknown exception occurred."
msgstr ""

#: heat/common/exception.py:113 heat/openstack/common/rpc/common.py:89
msgid "Exception in string format operation"
msgstr ""

#: heat/common/exception.py:125
#, python-format
msgid "Missing required credential: %(required)s"
msgstr ""

#: heat/common/exception.py:129
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""

#: heat/common/exception.py:134
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr ""

#: heat/common/exception.py:138
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr ""

#: heat/common/exception.py:142
msgid "Authorization failed."
msgstr ""

#: heat/common/exception.py:146
msgid "You are not authenticated."
msgstr ""

#: heat/common/exception.py:150 heat/common/exception.py:155
msgid "You are not authorized to complete this action."
msgstr ""

#: heat/common/exception.py:159
#, python-format
msgid "Data supplied was not valid: %(reason)s"
msgstr ""

#: heat/common/exception.py:163
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr ""

#: heat/common/exception.py:167
msgid "There was an error configuring the client."
msgstr ""

#: heat/common/exception.py:171
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""

#: heat/common/exception.py:177
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: heat/common/exception.py:188
msgid ""
"The request returned a 503 ServiceUnavilable. This generally occurs on "
"service overload or other transient outage."
msgstr ""

#: heat/common/exception.py:199
msgid "The URI was too long."
msgstr ""

#: heat/common/exception.py:203
#, python-format
msgid ""
"The request returned 500 Internal Server Error\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: heat/common/exception.py:208
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr ""

#: heat/common/exception.py:212
msgid "Received invalid HTTP redirect."
msgstr ""

#: heat/common/exception.py:216
msgid "Response from Keystone does not contain a Heat endpoint."
msgstr ""

#: heat/common/exception.py:220
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."
msgstr ""

#: heat/common/exception.py:226
#, python-format
msgid "The Parameter (%(key)s) was not provided."
msgstr ""

#: heat/common/exception.py:230
#, python-format
msgid "The Parameter (%(key)s) was not defined in template."
msgstr ""

#: heat/common/exception.py:234
#, python-format
msgid "The Referenced Attribute (%(resource)s %(key)s) is incorrect."
msgstr ""

#: heat/common/exception.py:239
#, python-format
msgid "The specified reference (%(resource)s %(key)s) is incorrect."
msgstr ""

#: heat/common/exception.py:244
#, python-format
msgid "The Key (%(key_name)s) could not be found."
msgstr ""

#: heat/common/exception.py:248
#, python-format
msgid "The Flavor ID (%(flavor_id)s) could not be found."
msgstr ""

#: heat/common/exception.py:252
#, python-format
msgid "The Image (%(image_name)s) could not be found."
msgstr ""

#: heat/common/exception.py:256
#, python-format
msgid "Multiple images were found with name (%(image_name)s)."
msgstr ""

#: heat/common/exception.py:260
#, python-format
msgid "Searching Tenant %(target)s from Tenant %(actual)s forbidden."
msgstr ""

#: heat/common/exception.py:265
#, python-format
msgid "The Stack (%(stack_name)s) could not be found."
msgstr ""

#: heat/common/exception.py:269
#, python-format
msgid "The Stack (%(stack_name)s) already exists."
msgstr ""

#: heat/common/exception.py:273
#, python-format
msgid "%(message)s"
msgstr ""

#: heat/common/exception.py:277
#, python-format
msgid ""
"The Resource (%(resource_name)s) could not be found in Stack "
"%(stack_name)s."
msgstr ""

#: heat/common/exception.py:282
#, python-format
msgid "The Resource Type (%(type_name)s) could not be found."
msgstr ""

#: heat/common/exception.py:286
#, python-format
msgid "The Resource (%(resource_name)s) is not available."
msgstr ""

#: heat/common/exception.py:290
#, python-format
msgid "The Resource (%(resource_id)s) could not be found."
msgstr ""

#: heat/common/exception.py:294
#, python-format
msgid "The Watch Rule (%(watch_name)s) could not be found."
msgstr ""

#: heat/common/exception.py:298
#, python-format
msgid "%(exc_type)s: %(message)s"
msgstr ""

#: heat/common/exception.py:312
#, python-format
msgid "%(feature)s is not supported."
msgstr ""

#: heat/common/exception.py:316
#, python-format
msgid "Cannot define the following properties at the same time: %s."
msgstr ""

#: heat/common/exception.py:334
msgid "Template exceeds maximum allowed size."
msgstr ""

#: heat/common/exception.py:338
msgid ""
"Egress rules are only allowed when Neutron is used and the 'VpcId' "
"property is set."
msgstr ""

#: heat/common/plugin_loader.py:94
#, python-format
msgid "Failed to import module %s"
msgstr ""

#: heat/common/urlfetch.py:37
#, python-format
msgid "Fetching data from %s"
msgstr ""

#: heat/common/wsgi.py:55
msgid ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."
msgstr ""

#: heat/common/wsgi.py:58
msgid "The port on which the server will listen."
msgstr ""

#: heat/common/wsgi.py:65
msgid "Number of backlog requests to configure the socket with"
msgstr ""

#: heat/common/wsgi.py:68
msgid "Location of the SSL Certificate File to use for SSL mode"
msgstr ""

#: heat/common/wsgi.py:71
msgid "Location of the SSL Key File to use for enabling SSL mode"
msgstr ""

#: heat/common/wsgi.py:78
msgid "Number of workers for Heat service"
msgstr ""

#: heat/common/wsgi.py:129 heat/openstack/common/sslutils.py:61
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: heat/common/wsgi.py:147
#, python-format
msgid "Could not bind to %(bind_addr)safter trying for 30 seconds"
msgstr ""

#: heat/common/wsgi.py:179
msgid "SIGTERM received"
msgstr ""

#: heat/common/wsgi.py:188
msgid "SIGHUP received"
msgstr ""

#: heat/common/wsgi.py:203 heat/openstack/common/service.py:288
#, python-format
msgid "Starting %d workers"
msgstr ""

#: heat/common/wsgi.py:214
#, python-format
msgid "Removing dead child %s"
msgstr ""

#: heat/common/wsgi.py:221
msgid "Caught keyboard interrupt. Exiting."
msgstr ""

#: heat/common/wsgi.py:225
msgid "Exited"
msgstr ""

#: heat/common/wsgi.py:243
#, python-format
msgid "Child %d exiting normally"
msgstr ""

#: heat/common/wsgi.py:246
#, python-format
msgid "Started child %s"
msgstr ""

#: heat/common/wsgi.py:268
msgid "Starting single process server"
msgstr ""

#: heat/common/wsgi.py:596
#, python-format
msgid "Exception handling resource: %s"
msgstr ""

#: heat/common/wsgi.py:597
msgid ""
"The server could not comply with the request since\r\n"
"it is either malformed or otherwise incorrect.\r\n"
msgstr ""

#: heat/common/wsgi.py:611
#, python-format
msgid "Returning %(code)s to user: %(explanation)s"
msgstr ""

#: heat/common/wsgi.py:616
#, python-format
msgid "Unexpected error occurred serving API: %s"
msgstr ""

#: heat/db/sqlalchemy/api.py:393
msgid "age should be an integer"
msgstr ""

#: heat/db/sqlalchemy/api.py:395
msgid "age should be a positive integer"
msgstr ""

#: heat/db/sqlalchemy/migration.py:63
msgid "python-migrate is not installed. Exiting."
msgstr ""

#: heat/db/sqlalchemy/migration.py:73
msgid "version should be an integer"
msgstr ""

#: heat/doc/resources.py:85
msgid "HOT Syntax"
msgstr ""

#: heat/doc/resources.py:107
msgid "YAML Syntax"
msgstr ""

#: heat/doc/resources.py:129
msgid "JSON Syntax"
msgstr ""

#: heat/doc/resources.py:161
#, python-format
msgid " from %s"
msgstr ""

#: heat/doc/resources.py:163
#, python-format
msgid " up to %s"
msgstr ""

#: heat/doc/resources.py:165
#, python-format
msgid " from length %s"
msgstr ""

#: heat/doc/resources.py:167
#, python-format
msgid " up to length %s"
msgstr ""

#: heat/doc/resources.py:174
msgid "Not implemented."
msgstr ""

#: heat/doc/resources.py:185
msgid "Required property."
msgstr ""

#: heat/doc/resources.py:189
#, python-format
msgid "Optional property, defaults to \"%s\"."
msgstr ""

#: heat/doc/resources.py:192
msgid "Optional property."
msgstr ""

#: heat/doc/resources.py:196
#, python-format
msgid "Value must match pattern: %s"
msgstr ""

#: heat/doc/resources.py:203
#, python-format
msgid "Allowed values: %s"
msgstr ""

#: heat/doc/resources.py:209
msgid "Map properties:"
msgstr ""

#: heat/doc/resources.py:215
msgid "List contains maps with the properties:"
msgstr ""

#: heat/doc/resources.py:230
msgid "Properties"
msgstr ""

#: heat/doc/resources.py:241
msgid "Attributes"
msgstr ""

#: heat/engine/dependencies.py:25
#, python-format
msgid "Circular Dependency Found: %(cycle)s"
msgstr ""

#: heat/engine/environment.py:181
#, python-format
msgid "Changing %(path)s from %(was)s to %(now)s"
msgstr ""

#: heat/engine/environment.py:183
#, python-format
msgid "Registering %(path)s -> %(value)s"
msgstr ""

#: heat/engine/parser.py:74
#, python-format
msgid ""
"Invalid stack name %s must contain only alphanumeric or \"_-.\" "
"characters, must start with alpha"
msgstr ""

#: heat/engine/resource.py:55 heat/engine/resource.py:58
#, python-format
msgid "The Resource %s requires replacement."
msgstr ""

#: heat/engine/resource.py:132
msgid "Resource name may not contain \"/\""
msgstr ""

#: heat/engine/scheduler.py:65
#, python-format
msgid "%s Timed out"
msgstr ""

#: heat/engine/service.py:311
msgid "No Template provided."
msgstr ""

#: heat/engine/stack_resource.py:122
#, python-format
msgid "Cannot update %s, stack not created"
msgstr ""

#: heat/engine/stack_resource.py:151
#, python-format
msgid "Cannot suspend %s, stack not created"
msgstr ""

#: heat/engine/stack_resource.py:173
#, python-format
msgid "Cannot resume %s, stack not created"
msgstr ""

#: heat/engine/resources/__init__.py:39
#, python-format
msgid "Failed to load resources from %s"
msgstr ""

#: heat/engine/resources/instance.py:314
#, python-format
msgid "Build of server %(server)s failed: %(message)s (%(code)s)"
msgstr ""

#: heat/engine/resources/instance.py:321
#, python-format
msgid "Nova reported unexpected instance[%(name)s] status[%(status)s]"
msgstr ""

#: heat/engine/resources/instance.py:418
#, python-format
msgid "Cannot suspend %s, resource_id not set"
msgstr ""

#: heat/engine/resources/instance.py:424 heat/engine/resources/instance.py:478
#, python-format
msgid "Failed to find instance %s"
msgstr ""

#: heat/engine/resources/instance.py:455
#, python-format
msgid " nova reported unexpected instance[%(instance)s] status[%(status)s]"
msgstr ""

#: heat/engine/resources/instance.py:472
#, python-format
msgid "Cannot resume %s, resource_id not set"
msgstr ""

#: heat/engine/resources/nova_utils.py:221
#, python-format
msgid "Resizing to '%(flavor)s' failed, status '%(status)s'"
msgstr ""

#: heat/engine/resources/vpc.py:72
#, python-format
msgid "Multiple routers found with name %s"
msgstr ""

#: heat/engine/resources/neutron/loadbalancer.py:251
msgid "The ID of the load balancing pool"
msgstr ""

#: heat/engine/resources/neutron/loadbalancer.py:254
msgid "Port number on which the servers are running on the members"
msgstr ""

#: heat/engine/resources/neutron/loadbalancer.py:258
msgid "The list of Nova server IDs load balanced"
msgstr ""

#: heat/engine/resources/rackspace/cloud_loadbalancer.py:33
#, python-format
msgid "There was an error building the loadbalancer:%(lb_name)s."
msgstr ""

#: heat/openstack/common/eventlet_backdoor.py:142
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr ""

#: heat/openstack/common/exception.py:102
msgid "Uncaught exception"
msgstr ""

#: heat/openstack/common/excutils.py:62
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: heat/openstack/common/excutils.py:90
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: heat/openstack/common/fileutils.py:64
#, python-format
msgid "Reloading cached file %s"
msgstr ""

#: heat/openstack/common/lockutils.py:100
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: heat/openstack/common/lockutils.py:166
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr ""

#: heat/openstack/common/lockutils.py:175
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\""
msgstr ""

#: heat/openstack/common/lockutils.py:185
#, python-format
msgid "Created lock path: %s"
msgstr ""

#: heat/openstack/common/lockutils.py:203
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: heat/openstack/common/lockutils.py:207
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: heat/openstack/common/lockutils.py:244
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr ""

#: heat/openstack/common/lockutils.py:248
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr ""

#: heat/openstack/common/log.py:244
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: heat/openstack/common/log.py:336
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: heat/openstack/common/log.py:386
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: heat/openstack/common/log.py:556
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: heat/openstack/common/loopingcall.py:84
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: heat/openstack/common/loopingcall.py:91
msgid "in fixed duration looping call"
msgstr ""

#: heat/openstack/common/loopingcall.py:131
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: heat/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: heat/openstack/common/policy.py:75
msgid "JSON file containing policy"
msgstr ""

#: heat/openstack/common/policy.py:78
msgid "Rule enforced when requested rule is not found"
msgstr ""

#: heat/openstack/common/policy.py:92
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: heat/openstack/common/policy.py:177
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: heat/openstack/common/policy.py:207
msgid "Rules successfully reloaded"
msgstr ""

#: heat/openstack/common/policy.py:253
#, python-format
msgid "Rule %s will be now enforced"
msgstr ""

#: heat/openstack/common/policy.py:268
#, python-format
msgid "Rule [%s] doesn't exist"
msgstr ""

#: heat/openstack/common/policy.py:478
#, python-format
msgid "Failed to understand rule %s"
msgstr ""

#: heat/openstack/common/policy.py:488
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: heat/openstack/common/policy.py:759
#, python-format
msgid "Failed to understand rule %r"
msgstr ""

#: heat/openstack/common/processutils.py:127
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: heat/openstack/common/processutils.py:142
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: heat/openstack/common/processutils.py:167
#: heat/openstack/common/processutils.py:240
#, python-format
msgid "Result was %s"
msgstr ""

#: heat/openstack/common/processutils.py:179
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: heat/openstack/common/processutils.py:219
#, python-format
msgid "Running cmd (SSH): %s"
msgstr ""

#: heat/openstack/common/processutils.py:221
msgid "Environment not supported over SSH"
msgstr ""

#: heat/openstack/common/processutils.py:225
msgid "process_input not supported over SSH"
msgstr ""

#: heat/openstack/common/service.py:118 heat/openstack/common/service.py:335
msgid "Full set of CONF:"
msgstr ""

#: heat/openstack/common/service.py:127 heat/openstack/common/service.py:217
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: heat/openstack/common/service.py:139
msgid "Exception during rpc cleanup."
msgstr ""

#: heat/openstack/common/service.py:188
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: heat/openstack/common/service.py:223
msgid "Unhandled exception"
msgstr ""

#: heat/openstack/common/service.py:256
msgid "Forking too fast, sleeping"
msgstr ""

#: heat/openstack/common/service.py:278
#, python-format
msgid "Started child %d"
msgstr ""

#: heat/openstack/common/service.py:305
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: heat/openstack/common/service.py:309
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr ""

#: heat/openstack/common/service.py:313
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: heat/openstack/common/service.py:345
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: heat/openstack/common/service.py:363
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: heat/openstack/common/sslutils.py:52
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: heat/openstack/common/sslutils.py:55
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: heat/openstack/common/sslutils.py:58
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: heat/openstack/common/sslutils.py:100
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: heat/openstack/common/db/exception.py:44
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: heat/openstack/common/db/sqlalchemy/session.py:552
msgid "DB exception wrapped."
msgstr ""

#: heat/openstack/common/db/sqlalchemy/session.py:614
#, python-format
msgid "Got mysql server has gone away: %s"
msgstr ""

#: heat/openstack/common/db/sqlalchemy/session.py:694
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr ""

#: heat/openstack/common/db/sqlalchemy/utils.py:50
msgid "Sort key supplied was not valid."
msgstr ""

#: heat/openstack/common/db/sqlalchemy/utils.py:89
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: heat/openstack/common/db/sqlalchemy/utils.py:111
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: heat/openstack/common/db/sqlalchemy/utils.py:182
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""

#: heat/openstack/common/db/sqlalchemy/utils.py:188
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."
msgstr ""

#: heat/openstack/common/db/sqlalchemy/utils.py:268
#, python-format
msgid "Deleting duplicated row with id: %(id)s from table: %(table)s"
msgstr ""

#: heat/openstack/common/db/sqlalchemy/utils.py:290
msgid "Unsupported id columns type"
msgstr ""

#: heat/openstack/common/notifier/api.py:129
#, python-format
msgid "%s not in valid priorities"
msgstr ""

#: heat/openstack/common/notifier/api.py:145
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""

#: heat/openstack/common/notifier/api.py:164
#, python-format
msgid "Failed to load notifier %s. These notifications will not be sent."
msgstr ""

#: heat/openstack/common/notifier/list_notifier.py:112
#, python-format
msgid "Problem '%(e)s' attempting to send to notification driver %(driver)s."
msgstr ""

#: heat/openstack/common/notifier/rabbit_notifier.py:27
msgid "The rabbit_notifier is now deprecated. Please use rpc_notifier instead."
msgstr ""

#: heat/openstack/common/notifier/rpc_notifier.py:45
#: heat/openstack/common/notifier/rpc_notifier2.py:51
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr ""

#: heat/openstack/common/rpc/__init__.py:107
#, python-format
msgid ""
"A RPC is being made while holding a lock. The locks currently held are "
"%(locks)s. This is probably a bug. Please report it. Include the "
"following: [%(stack)s]."
msgstr ""

#: heat/openstack/common/rpc/amqp.py:75
msgid "Pool creating new connection"
msgstr ""

#: heat/openstack/common/rpc/amqp.py:202
#, python-format
msgid "No calling threads waiting for msg_id : %(msg_id)s, message : %(data)s"
msgstr ""

#: heat/openstack/common/rpc/amqp.py:205
#, python-format
msgid "_call_waiters: %s"
msgstr ""

#: heat/openstack/common/rpc/amqp.py:212
#, python-format
msgid ""
"Number of call waiters is greater than warning threshhold: %d. There "
"could be a MulticallProxyWaiter leak."
msgstr ""

#: heat/openstack/common/rpc/amqp.py:290
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: heat/openstack/common/rpc/amqp.py:336
#, python-format
msgid "UNIQUE_ID is %s."
msgstr ""

#: heat/openstack/common/rpc/amqp.py:408
#, python-format
msgid "received %s"
msgstr ""

#: heat/openstack/common/rpc/amqp.py:416
#, python-format
msgid "no method for message: %s"
msgstr ""

#: heat/openstack/common/rpc/amqp.py:417
#, python-format
msgid "No method for message: %s"
msgstr ""

#: heat/openstack/common/rpc/amqp.py:445
#: heat/openstack/common/rpc/impl_zmq.py:280
#, python-format
msgid "Expected exception during message handling (%s)"
msgstr ""

#: heat/openstack/common/rpc/amqp.py:453
#: heat/openstack/common/rpc/impl_zmq.py:286
msgid "Exception during message handling"
msgstr ""

#: heat/openstack/common/rpc/amqp.py:527
#, python-format
msgid "Making synchronous call on %s ..."
msgstr ""

#: heat/openstack/common/rpc/amqp.py:530
#, python-format
msgid "MSG_ID is %s"
msgstr ""

#: heat/openstack/common/rpc/amqp.py:556
#, python-format
msgid "Making asynchronous cast on %s..."
msgstr ""

#: heat/openstack/common/rpc/amqp.py:565
msgid "Making asynchronous fanout cast..."
msgstr ""

#: heat/openstack/common/rpc/amqp.py:593
#, python-format
msgid "Sending %(event_type)s on %(topic)s"
msgstr ""

#: heat/openstack/common/rpc/common.py:77
msgid "An unknown RPC related exception occurred."
msgstr ""

#: heat/openstack/common/rpc/common.py:107
#, python-format
msgid ""
"Remote error: %(exc_type)s %(value)s\n"
"%(traceback)s."
msgstr ""

#: heat/openstack/common/rpc/common.py:124
#, python-format
msgid ""
"Timeout while waiting on RPC response - topic: \"%(topic)s\", RPC method:"
" \"%(method)s\" info: \"%(info)s\""
msgstr ""

#: heat/openstack/common/rpc/common.py:141
#: heat/openstack/common/rpc/common.py:142
#: heat/openstack/common/rpc/common.py:143
msgid "<unknown>"
msgstr ""

#: heat/openstack/common/rpc/common.py:147
#, python-format
msgid "Found duplicate message(%(msg_id)s). Skipping it."
msgstr ""

#: heat/openstack/common/rpc/common.py:151
msgid "Invalid reuse of an RPC connection."
msgstr ""

#: heat/openstack/common/rpc/common.py:155
#, python-format
msgid "Specified RPC version, %(version)s, not supported by this endpoint."
msgstr ""

#: heat/openstack/common/rpc/common.py:160
#, python-format
msgid ""
"Specified RPC envelope version, %(version)s, not supported by this "
"endpoint."
msgstr ""

#: heat/openstack/common/rpc/common.py:165
#, python-format
msgid "Specified RPC version cap, %(version_cap)s, is too low"
msgstr ""

#: heat/openstack/common/rpc/common.py:289
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: heat/openstack/common/rpc/impl_kombu.py:162
msgid "Failed to process message ... skipping it."
msgstr ""

#: heat/openstack/common/rpc/impl_kombu.py:165
msgid "Failed to process message ... will requeue."
msgstr ""

#: heat/openstack/common/rpc/impl_kombu.py:502
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: heat/openstack/common/rpc/impl_kombu.py:524
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: heat/openstack/common/rpc/impl_kombu.py:561
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""

#: heat/openstack/common/rpc/impl_kombu.py:575
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""

#: heat/openstack/common/rpc/impl_kombu.py:629
#: heat/openstack/common/rpc/impl_qpid.py:492
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""

#: heat/openstack/common/rpc/impl_kombu.py:647
#: heat/openstack/common/rpc/impl_qpid.py:507
#, python-format
msgid "Timed out waiting for RPC response: %s"
msgstr ""

#: heat/openstack/common/rpc/impl_kombu.py:651
#: heat/openstack/common/rpc/impl_qpid.py:511
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr ""

#: heat/openstack/common/rpc/impl_kombu.py:690
#: heat/openstack/common/rpc/impl_qpid.py:546
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""

#: heat/openstack/common/rpc/impl_qpid.py:161
msgid "Failed to process message... skipping it."
msgstr ""

#: heat/openstack/common/rpc/impl_qpid.py:434
#, python-format
msgid "Unable to connect to AMQP server: %(e)s. Sleeping %(delay)s seconds"
msgstr ""

#: heat/openstack/common/rpc/impl_qpid.py:440
#, python-format
msgid "Connected to AMQP server on %s"
msgstr ""

#: heat/openstack/common/rpc/impl_qpid.py:453
msgid "Re-established AMQP queues"
msgstr ""

#: heat/openstack/common/rpc/impl_qpid.py:519
msgid "Error processing message.  Skipping it."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:96
msgid "JSON serialization failed."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:101
#, python-format
msgid "Deserializing: %s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:136
#, python-format
msgid "Connecting to %(addr)s with %(type)s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:137
#, python-format
msgid "-> Subscribed to %(subscribe)s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:138
#, python-format
msgid "-> bind: %(bind)s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:146
msgid "Could not open socket."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:158
#, python-format
msgid "Subscribing to %s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:200
msgid "You cannot recv on this socket."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:205
msgid "You cannot send on this socket."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:267
#, python-format
msgid "Running func with context: %s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:305
msgid "Sending reply"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:339
msgid "RPC message did not include method."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:371
msgid "Registering reactor"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:383
msgid "In reactor registered"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:387
msgid "Consuming socket"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:437
#, python-format
msgid "Creating proxy for topic: %s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:443
msgid "Topic contained dangerous characters."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:475
msgid "Topic socket file creation failed."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:481
#, python-format
msgid "Local per-topic backlog buffer full for topic %(topic)s. Dropping message."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:497
#, python-format
msgid "Required IPC directory does not exist at %s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:506
#, python-format
msgid "Permission denied to IPC directory at %s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:509
msgid "Could not create ZeroMQ receiver daemon. Socket may already be in use."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:543
#, python-format
msgid "CONSUMER RECEIVED DATA: %s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:562
msgid "ZMQ Envelope version unsupported or unknown."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:590
msgid "Skipping topic registration. Already registered."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:597
#, python-format
msgid "Consumer is a zmq.%s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:649
msgid "Creating payload"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:662
msgid "Creating queue socket for reply waiter"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:675
msgid "Sending cast"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:678
msgid "Cast sent; Waiting reply"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:681
#, python-format
msgid "Received message: %s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:682
msgid "Unpacking response"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:691
msgid "Unsupported or unknown ZMQ envelope returned."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:698
msgid "RPC Message Invalid."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:721
#, python-format
msgid "%(msg)s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:724
#, python-format
msgid "Sending message(s) to: %s"
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:728
msgid "No matchmaker results. Not casting."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:731
msgid "No match from matchmaker."
msgstr ""

#: heat/openstack/common/rpc/impl_zmq.py:813
#, python-format
msgid "rpc_zmq_matchmaker = %(orig)s is deprecated; use %(new)s instead"
msgstr ""

#: heat/openstack/common/rpc/matchmaker.py:47
msgid "Match not found by MatchMaker."
msgstr ""

#: heat/openstack/common/rpc/matchmaker.py:81
msgid "Matchmaker does not implement registration or heartbeat."
msgstr ""

#: heat/openstack/common/rpc/matchmaker.py:217
#, python-format
msgid "Matchmaker unregistered: %(key)s, %(host)s"
msgstr ""

#: heat/openstack/common/rpc/matchmaker.py:229
msgid "Register before starting heartbeat."
msgstr ""

#: heat/openstack/common/rpc/matchmaker_ring.py:77
#: heat/openstack/common/rpc/matchmaker_ring.py:95
#, python-format
msgid "No key defining hosts for topic '%s', see ringfile"
msgstr ""

#: heat/openstack/common/rpc/service.py:49
#, python-format
msgid "Creating Consumer connection for Service %s"
msgstr ""

#: heat/tests/test_exception.py:24
#, python-format
msgid "Testing message %(text)s"
msgstr ""

